/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  guide: [
    'guide/intro'
  ],
  api: [
    'api/intro',
    {
      type: 'category',
      label: 'Iframe',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        'api/iframe/api-action-client',
        'api/iframe/custom-chart',
      ],
    },
    {
      type: 'category',
      label: 'REST API',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        'api/rest-api/authentication',
        'api/rest-api/api-action-server',
        'api/rest-api/accounts-management',
        'api/rest-api/errors',
      ],
    },
    'api/sclabjs'
  ],
};

module.exports = sidebars;
